@section('robots_all', robots('seo-home.index', 'home'))
@section('robots_google', robot_google('seo-home.index', 'home'))
@section('robots_yandex', robot_yandex('seo-home.index', 'home'))
@section('robots_bing', robot_bing('seo-home.index', 'home'))
@section('robots_yahoo', robot_yahoo('seo-home.index', 'home'))
@section('document_state', state('seo-home.document_state', 'home'))
@section('meta_title', meta_title('', url('/'), 'seo-home.meta_title'))
@section('meta_description', meta_description('', url('/'), 'seo-home.meta_description'))
@section('meta_keywords', meta_keywords('', url('/'), 'seo-home.meta_keywords'))
@section('json_ld', json_ld('', url('/'), 'seo-home.json_ld'))
@section('open_graph', open_graph('', url('/'), 'seo-home.open_graph'))