@section('robots_all', robots_all('home', null))
@section('robots_google', robots_google('home', null))
@section('robots_yandex', robots_yandex('home', null))
@section('robots_bing', robots_bing('home', null))
@section('robots_yahoo', robots_yahoo('home', null))
@section('robots_duck', robots_duck('home', null))
@section('robots_baidu', robots_baidu('home', null))
@section('document_state', state('home', null))
@section('meta_title', meta_title('home', url(''), null))
@section('meta_description', meta_description('home', url(''), null))
@section('meta_keywords', meta_keywords('home', url(''), null))
@section('json_ld', json_ld('home', url(''), null))
@section('open_graph', open_graph('home', url(''), null))
