@section('robots_all', robots($setting . '.index', $single->index))
@section('robots_google', robot_google($setting . '.index', $single->index))
@section('robots_yandex', robot_yandex($setting . '.index', $single->index))
@section('robots_bing', robot_bing($setting . '.index', $single->index))
@section('robots_yahoo', robot_yahoo($setting . '.index', $single->index))
@section('document_state', state($setting . '.document_state', $single->document_state))
@section('meta_title', meta_title($single, $url, $setting . '.meta_title'))
@section('meta_description', meta_description($single, $url, $setting . '.meta_description'))
@section('meta_keywords', meta_keywords($single, $url, $setting . '.meta_keywords'))
@section('json_ld', json_ld($single, $url, $setting . '.json_ld'))
@section('open_graph', open_graph($single, $url, $setting . '.open_graph'))