@section('robots_all', robots_all($key, $single->index))
@section('robots_google', robots_google($key, $single->index))
@section('robots_yandex', robots_yandex($key, $single->index))
@section('robots_bing', robots_bing($key, $single->index))
@section('robots_yahoo', robots_yahoo($key, $single->index))
@section('robots_duck', robots_duck($key, $single->index))
@section('robots_baidu', robots_baidu($key, $single->index))
@section('document_state', state($key, $single->document_state))
@section('meta_title', meta_title($key, $url, $single))
@section('meta_description', meta_description($key, $url, $single))
@section('meta_keywords', meta_keywords($key, $url, $single))
@section('json_ld', json_ld($key, $url, $single))
@section('open_graph', open_graph($key, $url, $single))
