@section('robots_all', robots($setting . '.index', $term->index))
@section('robots_google', robot_google($setting . '.index', $term->index))
@section('robots_yandex', robot_yandex($setting . '.index', $term->index))
@section('robots_bing', robot_bing($setting . '.index', $term->index))
@section('robots_yahoo', robot_yahoo($setting . '.index', $term->index))
@section('document_state', state($setting . '.document_state', $term->document_state))
@section('meta_title', meta_title($term, $url, $setting . '.meta_title'))
@section('meta_description', meta_description($term, $url, $setting . '.meta_description'))
@section('meta_keywords', meta_keywords($term, $url, $setting . '.meta_keywords'))
@section('json_ld', json_ld($term, $url, $setting . '.json_ld'))
@section('open_graph', open_graph($term, $url, $setting . '.open_graph'))